# Dependabot will run on day 18 of each month at 01:43 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "43 1 18 * *"
    open-pull-requests-limit: 20
    versioning-strategy: "increase"
    directories: "**/*"
