/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Default Gateway Key": {                         "en": "Default Gateway Key",                             "de": "Standard-Gateway-Schlüssel",                      "ru": "Ключ шлюза по умолчанию",                         "pt": "Chave de gateway padrão",                         "nl": "Standaard gatewaysleutel",                        "fr": "Clé de passerelle par défaut",                    "it": "Chiave gateway predefinita",                      "es": "Clave de puerta de enlace predeterminada",        "pl": "Domyślny klucz bramy",                            "zh-cn": "默认网关密钥："},
    "Device SID": {                                  "en": "Device SID",                                      "de": "Geräte-SID",                                      "ru": "SID устройства",                                  "pt": "SID do dispositivo",                              "nl": "Apparaat-SID",                                    "fr": "SID de l'appareil",                               "it": "SID del dispositivo",                             "es": "SID del dispositivo",                             "pl": "Identyfikator SID urządzenia",                    "zh-cn": "设备SID"},
    "Double key interval (ms)": {                    "en": "Double key interval (ms)",                        "de": "Doppelschlüsselintervall (ms)",                   "ru": "Двойной ключевой интервал (мс)",                  "pt": "Intervalo de chave dupla (ms)",                   "nl": "Dubbel sleutelinterval (ms)",                     "fr": "Intervalle de clé double (ms)",                   "it": "Doppio intervallo chiave (ms)",                   "es": "Intervalo de tecla doble (ms)",                   "pl": "Podwójny interwał klucza (ms)",                   "zh-cn": "双键间隔（毫秒）："},
    "Gateway Key": {                                 "en": "Gateway Key",                                     "de": "Gateway Schlussel",                               "ru": "Gateway ключ",                                    "pt": "Chave do Gateway",                                "nl": "Gateway-sleutel",                                 "fr": "Clé de la passerelle",                            "it": "Chiave di accesso",                               "es": "Clave de acceso",                                 "pl": "Klucz bramki",                                    "zh-cn": "网关密钥："},
    "Gateway keys": {                                "en": "Gateway keys",                                    "de": "Gateway-Schlüssel",                               "ru": "Ключи шлюза",                                     "pt": "Chaves de gateway",                               "nl": "Gateway sleutels",                                "fr": "Clés de passerelle",                              "it": "Chiavi del gateway",                              "es": "Claves de puerta de enlace",                      "pl": "Klucze do bram",                                  "zh-cn": "网关键"},
    "IP Address": {                                  "en": "IP-Address",                                      "de": "IP-Adresse",                                      "ru": "IP адрес",                                        "pt": "Endereço de IP",                                  "nl": "IP adres",                                        "fr": "Adresse IP",                                      "it": "Indirizzo IP",                                    "es": "Dirección IP",                                    "pl": "Adres IP",                                        "zh-cn": "IP地址"},
    "Key": {                                         "en": "Key",                                             "de": "Schlüssel",                                       "ru": "Ключ",                                            "pt": "Chave",                                           "nl": "Sleutel",                                         "fr": "Clé",                                             "it": "Chiave",                                          "es": "Llave",                                           "pl": "Klucz",                                           "zh-cn": "键"},
    "Listen on all IPs": {                           "en": "Listen on all IPs",                               "de": "Auf allen IP Adressen hören",                     "ru": "Слушать на всех адресах",                         "pt": "Ouça todos os IPs",                               "nl": "Luister op alle IP's",                            "fr": "Écoutez sur toutes les adresses IP",              "it": "Ascolta su tutti gli IP",                         "es": "Escuchar en todas las direcciones IP",            "pl": "Posłuchaj na wszystkich IP",                      "zh-cn": "监听所有IP"},
    "Main settings": {                               "en": "Main settings",                                   "de": "Haupteinstellungen",                              "ru": "Основные параметры",                              "pt": "Configurações principais",                        "nl": "Belangrijkste instellingen",                      "fr": "Réglages principaux",                             "it": "Impostazioni principali",                         "es": "Ajustes principales",                             "pl": "Ustawienia główne",                               "zh-cn": "主要设定"},
    "MiHome Smarthome settings": {                   "en": "MiHome Smarthome settings",                       "de": "MiHome Smarthome settings",                       "ru": "MiHome Smarthome settings",                       "pt": "Configurações de MiHome Smarthome",               "nl": "MiHome Smarthome-instellingen",                   "fr": "MiHome Smarthome paramètres",                     "it": "Impostazioni MiHome Smarthome",                   "es": "Ajustes MiHome Smarthome",                        "pl": "Ustawienia MiHome Smarthome",                     "zh-cn": "小米网关设置"},
    "Model": {                                       "en": "Model",                                           "de": "Modell",                                          "ru": "Модель",                                          "pt": "Modelo",                                          "nl": "Model",                                           "fr": "Modèle",                                          "it": "Modello",                                         "es": "Modelo",                                          "pl": "Model",                                           "zh-cn": "模型"},
    "SID": {                                         "en": "SID",                                             "de": "SID",                                             "ru": "SID",                                             "pt": "SID",                                             "nl": "SID",                                             "fr": "SID",                                             "it": "SID",                                             "es": "SID",                                             "pl": "SID",                                             "zh-cn": "SID"},
    "Search": {                                      "en": "Search",                                          "de": "Suche",                                           "ru": "Поиск",                                           "pt": "Procurar",                                        "nl": "Zoeken",                                          "fr": "Chercher",                                        "it": "Ricerca",                                         "es": "Buscar",                                          "pl": "Szukaj",                                          "zh-cn": "搜索"},
    "Use mmHg units for pressure": {                 "en": "Use mmHg units for pressure",                     "de": "mmHg-Einheiten für den Druck verwenden",          "ru": "Единицы измерения давления в мм рт. Ст.",         "pt": "Use unidades mmHg para pressão",                  "nl": "Gebruik mmHg-eenheden voor druk",                 "fr": "Utilisez les unités mmHg pour la pression",       "it": "Utilizzare unità mmHg per la pressione",          "es": "Utilice unidades de mmHg para la presión",        "pl": "Użyj jednostek mmHg dla ciśnienia",               "zh-cn": "使用毫米汞柱压力单位"},
    "heartbeatTimeout": {                            "en": "Heartbeat timeout (ms)",                          "de": "Heartbeat-Timeout (ms)",                          "ru": "Тайм-аут сердечного ритма (мс)",                  "pt": "Tempo limite de pulsação (ms)",                   "nl": "Heartbeat time-out (ms)",                         "fr": "Délai d'attente de pulsation (ms)",               "it": "Timeout heartbeat (ms)",                          "es": "Tiempo de latido del corazón (ms)",               "pl": "Limit czasu bicia serca (ms)",                    "zh-cn": "心跳超时时间（ms）"},
    "ioBroker IP": {                                 "en": "ioBroker IP",                                     "de": "ioBroker IP",                                     "ru": "ioBroker IP",                                     "pt": "ioBroker IP",                                     "nl": "ioBroker IP",                                     "fr": "ioBroker IP",                                     "it": "IP ioBroker",                                     "es": "ioBroker IP",                                     "pl": "IP ioBroker",                                     "zh-cn": "ioBroker IP："},
    "ioBroker Port": {                               "en": "ioBroker Port",                                   "de": "ioBroker Port",                                   "ru": "ioBroker порт",                                   "pt": "ioBroker Port",                                   "nl": "ioBroker Port",                                   "fr": "ioBroker Port",                                   "it": "porta ioBroker",                                  "es": "Puerto ioBroker",                                 "pl": "Port ioBroker",                                   "zh-cn": "ioBroker端口："},
    "restartInterval": {                             "en": "Re-connection interval (ms)",                     "de": "Re-Verbindungsintervall (ms)",                    "ru": "Интервал повторного подключения (мс)",            "pt": "Intervalo de reconexão (ms)",                     "nl": "Re-connection interval (ms)",                     "fr": "Intervalle de reconnexion (ms)",                  "it": "Intervallo di ricollegamento (ms)",               "es": "Intervalo de reconexión (ms)",                    "pl": "Interwał ponownego połączenia (ms)",              "zh-cn": "重新连接间隔（ms）"},
};