/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Gateway Key:": {                                "en": "Gateway Key:",                                    "de": "Gateway Schlussel:",                              "ru": "Gateway ключ:",                                   "pt": "Chave do Gateway:",                               "nl": "Gateway-sleutel:",                                "fr": "Clé de la passerelle:",                           "it": "Chiave di accesso:",                              "es": "Clave de acceso:",                                "pl": "Klucz bramki:",                                   "zh-cn": "网关密钥："},
    "Listen on all IPs": {                           "en": "Listen on all IPs",                               "de": "Auf allen IP Adressen hören",                     "ru": "Слушать на всех адресах",                         "pt": "Ouça todos os IPs",                               "nl": "Luister op alle IP's",                            "fr": "Écoutez sur toutes les adresses IP",              "it": "Ascolta su tutti gli IP",                         "es": "Escuchar en todas las direcciones IP",            "pl": "Posłuchaj na wszystkich IP",                      "zh-cn": "监听所有IP"},
    "MiHome Smarthome settings": {                   "en": "MiHome Smarthome settings",                       "de": "MiHome Smarthome settings",                       "ru": "MiHome Smarthome settings",                       "pt": "Configurações de MiHome Smarthome",               "nl": "MiHome Smarthome-instellingen",                   "fr": "MiHome Smarthome paramètres",                     "it": "Impostazioni MiHome Smarthome",                   "es": "Ajustes MiHome Smarthome",                        "pl": "Ustawienia MiHome Smarthome",                     "zh-cn": "小米网关设置"},
    "heartbeatTimeout": {                            "en": "Heartbeat timeout (ms)",                          "de": "Heartbeat-Timeout (ms)",                          "ru": "Тайм-аут сердечного ритма (мс)",                  "pt": "Tempo limite de pulsação (ms)",                   "nl": "Heartbeat time-out (ms)",                         "fr": "Délai d'attente de pulsation (ms)",               "it": "Timeout heartbeat (ms)",                          "es": "Tiempo de latido del corazón (ms)",               "pl": "Limit czasu bicia serca (ms)",                    "zh-cn": "心跳超时时间（ms）"},
    "ioBroker IP:": {                                "en": "ioBroker IP:",                                    "de": "ioBroker IP:",                                    "ru": "ioBroker IP:",                                    "pt": "ioBroker IP:",                                    "nl": "ioBroker IP:",                                    "fr": "ioBroker IP:",                                    "it": "IP ioBroker:",                                    "es": "ioBroker IP:",                                    "pl": "IP ioBroker:",                                    "zh-cn": "ioBroker IP："},
    "ioBroker Port:": {                              "en": "ioBroker Port:",                                  "de": "ioBroker Port:",                                  "ru": "ioBroker порт:",                                  "pt": "ioBroker Port:",                                  "nl": "ioBroker Port:",                                  "fr": "ioBroker Port:",                                  "it": "porta ioBroker:",                                 "es": "Puerto ioBroker:",                                "pl": "Port ioBroker:",                                  "zh-cn": "ioBroker端口："},
    "restartInterval": {                             "en": "Re-connection interval (ms)",                     "de": "Re-Verbindungsintervall (ms)",                    "ru": "Интервал повторного подключения (мс)",            "pt": "Intervalo de reconexão (ms)",                     "nl": "Re-connection interval (ms)",                     "fr": "Intervalle de reconnexion (ms)",                  "it": "Intervallo di ricollegamento (ms)",               "es": "Intervalo de reconexión (ms)",                    "pl": "Interwał ponownego połączenia (ms)",              "zh-cn": "重新连接间隔（ms）"},
};