/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Gateway Key:": {                                "en": "Gateway Key:",                                    "de": "Gateway Schlussel:",                              "ru": "Gateway ключ:",                                   "pt": "Chave do Gateway:",                               "nl": "Gateway-sleutel:",                                "fr": "Clé de la passerelle:",                           "it": "Chiave di accesso:",                              "es": "Clave de acceso:",                                "pl": "Klucz bramki:"},
    "Listen on all IPs": {                           "en": "Listen on all IPs",                               "de": "Auf allen IP Adressen hören",                     "ru": "Слушать на всех адресах",                         "pt": "Ouça todos os IPs",                               "nl": "Luister op alle IP's",                            "fr": "Écoutez sur toutes les adresses IP",              "it": "Ascolta su tutti gli IP",                         "es": "Escuchar en todas las direcciones IP",            "pl": "Posłuchaj na wszystkich IP"},
    "MiHome Smarthome settings": {                   "en": "MiHome Smarthome settings",                       "de": "MiHome Smarthome settings",                       "ru": "MiHome Smarthome settings",                       "pt": "Configurações de MiHome Smarthome",               "nl": "MiHome Smarthome-instellingen",                   "fr": "MiHome Smarthome paramètres",                     "it": "Impostazioni MiHome Smarthome",                   "es": "Ajustes MiHome Smarthome",                        "pl": "Ustawienia MiHome Smarthome"},
    "ioBroker IP:": {                                "en": "ioBroker IP:",                                    "de": "ioBroker IP:",                                    "ru": "ioBroker IP:",                                    "pt": "ioBroker IP:",                                    "nl": "ioBroker IP:",                                    "fr": "ioBroker IP:",                                    "it": "IP ioBroker:",                                    "es": "ioBroker IP:",                                    "pl": "IP ioBroker:"},
    "ioBroker Port:": {                              "en": "ioBroker Port:",                                  "de": "ioBroker Port:",                                  "ru": "ioBroker порт:",                                  "pt": "ioBroker Port:",                                  "nl": "ioBroker Port:",                                  "fr": "ioBroker Port:",                                  "it": "porta ioBroker:",                                 "es": "Puerto ioBroker:",                                "pl": "Port ioBroker:"},
};